authapp/urls.py
from django.urls import path
from authapp.apps import AuthappConfig
from authapp.views import CustomLoginView, RegisterView, CustomLogoutView, EditView

app_name = AuthappConfig.name

urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    path("edit/<int:pk>/", EditView.as_view(), name="edit",),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
import debug_toolbar


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='mainapp/')),
    path('mainapp/', include('mainapp.urls', namespace='mainapp')),
    path('authapp/', include('authapp.urls', namespace='authapp')),
    path('social_auth/', include('social_django.urls', namespace='social')),
    path("i18n/", include("django.conf.urls.i18n")),
]

if settings.DEBUG:
    urlpatterns.append(path("__debug__/", include(debug_toolbar.urls)))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path
from mainapp import views
from mainapp.apps import MainappConfig
from django.views.decorators.cache import cache_page


app_name = MainappConfig.name


urlpatterns = [
    path("contacts/", views.ContactsView.as_view(), name='contacts'),
    path("docsite/", views.DocSiteView.as_view(), name='doc_site'),
    path("", views.IndexView.as_view(), name='main_page'),
    path("login/", views.LoginView.as_view(), name='login'),
    path("news/", views.NewsView.as_view(), name="news"),
    path("news/create/", views.NewsCreateView.as_view(), name="news_create"),
    path("news/<int:pk>/detail",
         views.NewsDetailView.as_view(), name="news_detail", ),
    path("news/<int:pk>/update",
         views.NewsUpdateView.as_view(), name="news_update", ),
    path("news/<int:pk>/delete",
         views.NewsDeleteView.as_view(), name="news_delete", ),
    path("courses/", cache_page(60*5) (views.CoursesView.as_view()), name="courses"),
    path("courses/<int:pk>/", views.CoursesDetailView.as_view(),
         name="courses_detail",),
    path("courses_feedback/", views.CourseFeedbackFormProcessView.as_view(),
         name="courses_feedback",),
     path("log_view/", views.LogView.as_view(), name="log_view"),
     path("log_download/", views.LogDownloadView.as_view(), name="log_download"),
]

mainapp/models.py
from tabnanny import verbose
from unittest.util import _MAX_LENGTH
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.contrib.auth import get_user_model


class News(models.Model):
    title = models.CharField(max_length=256, verbose_name='Заголовок')
    preamble = models.CharField(max_length=1024, verbose_name='Вступление')

    body = models.TextField(verbose_name="Содержимое")
    body_as_markdown = models.BooleanField(
        default=False, verbose_name="As markdown")

    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Создан")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Обновлен")
    deleted = models.BooleanField(default=False, verbose_name="Удалено")

    def __str__(self):
        return f"{self.title}"

    def delete(self, *args):
        self.deleted = True
        self.save()

    class Meta:
        verbose_name = _('новость')
        verbose_name_plural = _('новости')


class Course(models.Model):
    name = models.CharField(max_length=256, verbose_name="Заголовок")
    description = models.TextField(verbose_name="Описание")
    description_as_markdown = models.BooleanField(
        verbose_name="As markdown", default=False)

    cost = models.DecimalField(
        max_digits=8, decimal_places=2, verbose_name="Стоимость", default=0)
    cover = models.CharField(
        max_length=25, default="no_image.svg", verbose_name="Изображение")

    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Создан")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Обновлен")
    deleted = models.BooleanField(default=False, verbose_name="Удалено")

    def __str__(self):
        return f"{self.name}"

    def delete(self, *args):
        self.deleted = True
        self.save()

    class Meta:
        verbose_name = _('курс')
        verbose_name_plural = _('курсы')


class Lesson(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    num = models.PositiveIntegerField(verbose_name="Номер урока")
    title = models.CharField(max_length=256, verbose_name="Заголовок")
    description = models.TextField(verbose_name="Описание")
    description_as_markdown = models.BooleanField(
        verbose_name="As markdown", default=False)

    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Создан")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Обновлен")
    deleted = models.BooleanField(default=False, verbose_name="Удалено")

    def __str__(self):
        return f"№{self.num} {self.title}"

    def delete(self, *args):
        self.deleted = True
        self.save()

    class Meta:
        verbose_name = 'урок'
        verbose_name_plural = 'уроки'
        ordering = ("course", "num")


class CourseTeacher(models.Model):
    course = models.ManyToManyField(Course)
    first_name = models.CharField(max_length=128, verbose_name="Имя")
    last_name = models.CharField(max_length=128, verbose_name="Фамилия")

    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Создан")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Обновлен")
    deleted = models.BooleanField(default=False, verbose_name="Удалено")

    def __str__(self):
        return f"№{self.first_name} {self.last_name}"

    def delete(self, *args):
        self.deleted = True
        self.save()

    class Meta:
        verbose_name = 'курс к учителю'
        verbose_name_plural = 'курсы к учителям'


class CourseFeedback(models.Model):
    RATING = ((5, "⭐⭐⭐⭐⭐"), (4, "⭐⭐⭐⭐"), (3, "⭐⭐⭐"), (2, "⭐⭐"),
              (1, "⭐"))
    course = models.ForeignKey(
        Course, on_delete=models.CASCADE, verbose_name=_("Course"))
    user = models.ForeignKey(
        get_user_model(), on_delete=models.CASCADE, verbose_name=_("User"))
    feedback = models.TextField(
        default=_("No feedback"), verbose_name=_("Feedback"))
    rating = models.SmallIntegerField(
        choices=RATING, default=5, verbose_name=_("Rating"))
    created = models.DateTimeField(auto_now_add=True, verbose_name="Created")
    deleted = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.course} ({self.user})"

mainapp/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
from mainapp import models as mainapp_models


class CourseFeedbackForm(forms.ModelForm):
    def __init__(self, *args, course=None, user=None, **kwargs):
        ret = super().__init__(*args, **kwargs)
        if course and user:
            self.fields["course"].initial = course.pk
            self.fields["user"].initial = user.pk
        return ret

    class Meta:
        model = mainapp_models.CourseFeedback
        fields = ("course", "user", "feedback", "rating")
        widgets = {
            "course": forms.HiddenInput(),
            "user": forms.HiddenInput(),
            "rating": forms.RadioSelect(),
        }


class MailFeedbackForm(forms.Form):
    user_id = forms.IntegerField(widget=forms.HiddenInput)
    message = forms.CharField(
        widget=forms.Textarea,
        help_text=_("Enter your message"),
        label=_("Message"),
    )

    def __init__(self, *args, user=None, **kwargs):
        super().__init__(*args, **kwargs)
        if user:
            self.fields["user_id"].initial = user.pk

mainapp/views.py
# from django.shortcuts import render

# Create your views here.

from datetime import datetime
from django.http import HttpResponse, JsonResponse, FileResponse, HttpResponseRedirect
from django.views.generic import TemplateView, ListView, UpdateView, CreateView, DeleteView, DetailView, View
from django.shortcuts import get_object_or_404
from django.urls import reverse, reverse_lazy
from django.contrib import messages
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin, UserPassesTestMixin
from mainapp.forms import CourseFeedbackForm, MailFeedbackForm
from django.template.loader import render_to_string
from django.conf import settings
from mainapp import tasks as mainapp_tasks
from django.utils.translation import gettext_lazy as _
from django.core.cache import cache



from mainapp.models import News, Course, Lesson, CourseTeacher, CourseFeedback

import logging
logger = logging.getLogger(__name__)


class CoursesDetailView(TemplateView):
    template_name = "mainapp/courses_detail.html"

    def get_context_data(self, pk=None, **kwargs):
        logger.debug("Yet another log message")
        context = super(CoursesDetailView, self).get_context_data(**kwargs)
        context["course_object"] = get_object_or_404(Course, pk=pk)
        context["lessons"] = Lesson.objects.filter(
            course=context["course_object"])
        context["teachers"] = CourseTeacher.objects.filter(
            course=context["course_object"])
        if not self.request.user.is_anonymous:
            if not CourseFeedback.objects.filter(course=context["course_object"], user=self.request.user).count():
                context["feedback_form"] = CourseFeedbackForm(
                    course=context["course_object"], user=self.request.user)
            context["feedback_list"] = CourseFeedback.objects.filter(
                course=context["course_object"]).order_by("-created", "-rating")[:5]
        return context


class ContactsView(TemplateView):
    template_name = 'mainapp/contacts.html'

    def get_context_data(self, **kwargs):
        context = super(ContactsView, self).get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            context["form"] = MailFeedbackForm(user=self.request.user)
        return context

    def post(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            cache_lock_flag = cache.get(
                f"mail_feedback_lock_{self.request.user.pk}")
            if not cache_lock_flag:
                cache.set(
                    f"mail_feedback_lock_{self.request.user.pk}", "lock", timeout=300,)
                messages.add_message(self.request, messages.INFO, _("Message sended")
                                     )
                mainapp_tasks.send_feedback_mail.delay(
                    {
                        "user_id": self.request.POST.get("user_id"),
                        "message": self.request.POST.get("message"),
                    }
                )
            else:
                messages.add_message(self.request, messages.WARNING, _(
                    "You can send only one message per 5 minutes"), )

        return HttpResponseRedirect(reverse_lazy("mainapp:contacts"))


class CoursesView(ListView):
    model = Course


class CoursesDetailView(TemplateView):
    template_name = "mainapp/courses_detail.html"

    def get_context_data(self, pk=None, **kwargs):
        logger.debug("Yet another log message")
        context = super(CoursesDetailView, self).get_context_data(**kwargs)
        context["course_object"] = get_object_or_404(Course, pk=pk)
        context["lessons"] = Lesson.objects.filter(course=context["course_object"])
        context["teachers"] = CourseTeacher.objects.filter(course=context["course_object"])
        if not self.request.user.is_anonymous:
            if not CourseFeedback.objects.filter(
                course=context["course_object"], user=self.request.user
            ).count():
                context["feedback_form"] = CourseFeedbackForm(
                    course=context["course_object"], user=self.request.user
                )

        cached_feedback = cache.get(f"feedback_list_{pk}")
        if not cached_feedback:
            context["feedback_list"] = (
                CourseFeedback.objects.filter(course=context["course_object"])
                .order_by("-created", "-rating")[:5]
                .select_related()
            )
            cache.set(f"feedback_list_{pk}", context["feedback_list"], timeout=300)  # 5 minutes

            # Archive object for tests --->
            import pickle

            with open(f"mainapp/fixtures/005_feedback_list_{pk}.bin", "wb") as outf:
                pickle.dump(context["feedback_list"], outf)
            # <--- Archive object for tests

        else:
            context["feedback_list"] = cached_feedback

        return context


class CourseFeedbackFormProcessView(LoginRequiredMixin, CreateView):
    model = CourseFeedback
    form_class = CourseFeedbackForm

    def form_valid(self, form):
        self.object = form.save()
        rendered_card = render_to_string(
            "mainapp/includes/feedback_card.html", context={"item": self.object})

        return JsonResponse({"card": rendered_card})


class DocSiteView(TemplateView):
    template_name = 'mainapp/doc_site.html'


class IndexView(TemplateView):
    template_name = 'mainapp/index.html'


class LoginView(TemplateView):
    template_name = 'mainapp/login.html'


class NewsView(ListView):
    model = News
    paginate_by = 5

    def get_queryset(self):
        return super().get_queryset().filter(deleted=False)


class NewsCreateView(PermissionRequiredMixin, CreateView):
    model = News
    fields = "__all__"
    success_url = reverse_lazy("mainapp:news")
    permission_required = ("mainapp.add_news",)


class NewsDetailView(DetailView):
    model = News


class NewsUpdateView(PermissionRequiredMixin, UpdateView):

    model = News
    fields = "__all__"
    success_url = reverse_lazy("mainapp:news")
    permission_required = ("mainapp.change_news",)


class NewsDeleteView(PermissionRequiredMixin, DeleteView):
    model = News
    success_url = reverse_lazy("mainapp:news")
    permission_required = ("mainapp.delete_news",)


class LogView(TemplateView):
    template_name = "mainapp/log_view.html"

    def get_context_data(self, **kwargs):
        context = super(LogView, self).get_context_data(**kwargs)
        log_slice = []
        with open(settings.LOG_FILE, "r") as log_file:
            for i, line in enumerate(log_file):
                if i == 1000:  # first 1000 lines
                    break
                log_slice.insert(0, line)  # append at start
            context["log"] = "".join(log_slice)
        return context


class LogDownloadView(UserPassesTestMixin, View):
    def test_func(self):
        return self.request.user.is_superuser

    def get(self, *args, **kwargs):
        return FileResponse(open(settings.LOG_FILE, "rb"))

mainapp/templates/mainapp/includes/feedback_card.html
<div class="card mb-3">
    <div class="card-body">
        <h5 class="card-title">{{ item.get_rating_display }}</h5>
        <h6 class="card-subtitle mb-2 text-muted">{{ item.user }}</h6>
        <p class="card-text">
            {{ item.feedback }}
        </p>
    </div>
</div>

mainapp/templates/mainapp/includes/inc_menu.html
{% load static i18n %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="{% url 'mainapp:main_page' %}">
            <img src="{% static 'img/logo.png' %}" alt="">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item {% if request.resolver_match.view_name == 'mainapp:news' %}active{% endif %}">
                    <a class="nav-link" href="{% url 'mainapp:news' %}">{% translate 'Новости' %}</a>
                </li>
                <li class="nav-item {% if request.resolver_match.view_name == 'mainapp:courses' %}active{% endif %}">
                    <a class="nav-link" href="{% url 'mainapp:courses' %}">{% translate 'Курсы' %}</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="ddProfile" role="button" data-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="false">
                        {% translate 'Профиль' %}
                    </a>
                    <div class="dropdown-menu" aria-labelledby="ddProfile">
                        <a class="dropdown-item" href="{% url 'authapp:edit' pk=request.user.pk%}">Редактировать
                            профиль</a>
                        <a class="dropdown-item" href="#">Мои курсы</a>
                        <div class="dropdown-divider"></div>
                        {% if user.is_staff %}
                        <a class="dropdown-item" href="{% url 'admin:index' %}">Модерация</a>
                        {% endif %}
                        {% if user.is_superuser %}
                        <a class="dropdown-item" href="{% url 'admin:index' %}" target="_blank">Административный
                            раздел</a>
                        <a class="dropdown-item" href="{% url 'mainapp:log_view' %}" target="_blank">Лог</a>
                        {% endif %}
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'authapp:logout' %}">{% translate 'Выход' %}</a>
                    </div>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'authapp:login' %}">{% translate 'Вход' %}</a>
                </li>
                {% endif %}
                <li class="nav-item {% if request.resolver_match.view_name == 'mainapp:contacts' %}active{% endif %}">
                    <a class="nav-link" href="{% url 'mainapp:contacts' %}">{% translate 'Контакты' %}</a>
                </li>
            </ul>
            <div class="row justify-content-end m-0">
                <div class="col p-0 border-right">
                    <form action="{% url 'set_language' %}" method="post">
                        {% csrf_token %}
                        <input name="language" type="hidden" value="ru">
                        <button type="submit" class="btn btn-link">RU</button>
                    </form>
                </div>
                <div class="col p-0 border-left">
                    <form action="{% url 'set_language' %}" method="post">
                        {% csrf_token %}
                        <input name="language" type="hidden" value="en">
                        <button type="submit" class="btn btn-link">GB</button>
                    </form>
                </div>
            </div>

        </div>
    </div>
</nav>