authapp/urls.py
from django.urls import path
from authapp.apps import AuthappConfig
from authapp.views import CustomLoginView, RegisterView, CustomLogoutView, EditView

app_name = AuthappConfig.name

urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    path("edit/<int:pk>/", EditView.as_view(), name="edit",),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
import debug_toolbar


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='mainapp/')),
    path('mainapp/', include('mainapp.urls', namespace='mainapp')),
    path('authapp/', include('authapp.urls', namespace='authapp')),
    path('social_auth/', include('social_django.urls', namespace='social')),
    path("i18n/", include("django.conf.urls.i18n")),
]

if settings.DEBUG:
    urlpatterns.append(path("__debug__/", include(debug_toolbar.urls)))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path
from mainapp import views
from mainapp.apps import MainappConfig
from django.views.decorators.cache import cache_page


app_name = MainappConfig.name


urlpatterns = [
    path("contacts/", views.ContactsView.as_view(), name='contacts'),
    path("docsite/", views.DocSiteView.as_view(), name='doc_site'),
    path("", views.IndexView.as_view(), name='main_page'),
    path("login/", views.LoginView.as_view(), name='login'),
    path("news/", views.NewsView.as_view(), name="news"),
    path("news/create/", views.NewsCreateView.as_view(), name="news_create"),
    path("news/<int:pk>/detail",
         views.NewsDetailView.as_view(), name="news_detail", ),
    path("news/<int:pk>/update",
         views.NewsUpdateView.as_view(), name="news_update", ),
    path("news/<int:pk>/delete",
         views.NewsDeleteView.as_view(), name="news_delete", ),
    path("courses/", cache_page(60*5) (views.CoursesView.as_view()), name="courses"),
    path("courses/<int:pk>/", views.CoursesDetailView.as_view(),
         name="courses_detail",),
    path("courses_feedback/", views.CourseFeedbackFormProcessView.as_view(),
         name="courses_feedback",),
     path("log_view/", views.LogView.as_view(), name="log_view"),
     path("log_download/", views.LogDownloadView.as_view(), name="log_download"),
]

authapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    email = models.EmailField(verbose_name='Email', blank=True, unique=True)
    age = models.PositiveIntegerField(null=True, blank=True, verbose_name='Возраст')
    avatar = models.ImageField(upload_to='users', blank=True, null=True)

    class Meta:
        verbose_name = 'пользователь'
        verbose_name_plural = 'пользователи'

authapp/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UsernameField, UserChangeForm
from django.core.exceptions import ValidationError
import os
from django.utils.translation import gettext_lazy as _



class CustomUserCreationForm(UserCreationForm):

    class Meta:

        model = get_user_model()
        fields = (
            "username",
            "email",
            "first_name",
            "last_name",
            "age",
            "avatar",
        )
        field_classes = {"username": UsernameField}


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = (
            "username",
            "email",
            "first_name",
            "last_name",
            "age",
            "avatar",
        )
        field_classes = {"username": UsernameField}
        def clean_avatar(self):
            arg_as_str = "avatar"
            if arg_as_str in self.changed_data and self.instance.avatar:
                if os.path.exists(self.instance.avatar.path):
                    os.remove(self.instance.avatar.path)
            return self.cleaned_data.get(arg_as_str)
        def clean_age(self):
            data = self.cleaned_data.get("age")
            if data < 10 or data > 100:
                raise ValidationError(_("Please, enter a valid age!"))
            return data

authapp/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, ListView, CreateView, UpdateView
from django.contrib import messages
from authapp.models import User
from authapp.forms import CustomUserCreationForm, CustomUserChangeForm
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib.auth import get_user_model
from django.http.response import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.contrib.auth.views import LoginView, LogoutView


class CustomLoginView(LoginView):
    template_name = 'authapp/login.html'
    extra_context = {
        'title': 'Вход пользователя'
    }


class RegisterView(CreateView):
    model = get_user_model()
    form_class = CustomUserCreationForm
    success_url = reverse_lazy("mainapp:main_page")


class CustomLogoutView(LogoutView):
    pass


class EditView(UserPassesTestMixin, UpdateView):

    model = get_user_model()
    form_class = CustomUserChangeForm

    def test_func(self):
        return True if self.request.user.pk == self.kwargs.get("pk") else False

    def get_success_url(self):
        return reverse_lazy("authapp:edit", args=[self.request.user.pk])

authapp/templates/authapp/base.html
{% load static %}

<!doctype html>
<html lang="ru">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

  <!-- ChartJS -->
  <link rel="stylesheet" href="{% static 'css/Chart.min.css' %}">

  <!-- FontAwesome -->
  <link rel="stylesheet" href="{% static 'css/fontawesome.all.min.css' %}">

  <title>Welcome to GeekLab!</title>
</head>

<body>

  {% include 'authapp/includes/inc_messages.html' %}



  <div class="row justify-content-around align-items-center" style="height: 100vh; margin: 0px">
    <div class="text-center">
      <p>
        <a href="{% url 'mainapp:main_page' %}"><img src="{% static 'img/logo.png' %}" alt=""></a>
      </p>
      <h2>{{ title }}</h2>
      {% block content %}
      {% endblock %}
      <h4>Вход через социальные сети</h4>
      <p>
      <div class="btn-group btn-block" role="group">
        <a class="btn btn-primary" href="#" role="button"><i class="fab fa-vk"></i></a>
        <a class="btn btn-primary" href="{% url 'social:begin' 'github' %}" role="button"><i
            class="fab fa-github"></i></a>
        <a class="btn btn-primary" href="#" role="button"><i class="fab fa-facebook"></i></a>
      </div>
      </p>
    </div>
  </div>


  <!-- JavaScript section -->
  <!-- Bootstrap -->
  <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
  <script src="{% static 'js/popper.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>

  <!-- ChartJs -->
  <script src="{% static 'js/Chart.min.js' %}"></script>

  <!-- FontAwesome -->
  <script src="{% static 'js/fontawesome.all.min.js' %}"></script>

  {% block js %}
  {% endblock %}

</body>

</html>

authapp/templates/authapp/edit.html
{% extends 'mainapp/base.html' %}
{% block content %}
<form class="col-6 m-auto pt-5 pb-5" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <p>
        <input type="text" name="username" autofocus="" autocapitalize="none" value="{{ user.username }}" autocomplete="username" maxlength="150"
            class="textinput textInput form-control" required="" id="id_username" placeholder="Username">
    </p>
    <p>
        <input type="text" name="email" autofocus="" autocapitalize="none" value="{{ user.email }}" autocomplete="email" maxlength="150"
            class="textinput textInput form-control" required="" id="id_email" placeholder="Email">
    </p>
    <p>
        <input type="text" name="first_name" value="{{ user.first_name }}" autocapitalize="none" maxlength="150"
            class="textinput textInput form-control" required="" placeholder="First name">
    </p>
    <p>
        <input type="text" name="last_name" value="{{ user.last_name }}" autocapitalize="none" maxlength="150"
        class="textinput textInput form-control" required="" placeholder="Last name">
    </p>
    <p>
        <input type="number" name="age" value="{{ user.age }}" autocapitalize="none"
        class="textinput textInput form-control" required="" placeholder="Age">
    </p>
    <p>
        <input type="file" name="avatar" class="textinput textInput form-control" required="" placeholder="Avatar">
    </p>
    <p>
        <button type="submit" class="btn btn-primary btn-block">Сохранить</button>
    </p>
</form>


{% endblock %}

{% block js %}

<script>
    $(document).ready(function () {
        {% if messages %}
        // Toasts
        $(".toast").toast({ delay: 5000 });
        $(".toast").toast("show");
        {% endif %}
    });
</script>

{% endblock %}

authapp/templates/authapp/login.html
{% extends 'authapp/base.html' %}
{% block content %}
<form method="post">
  {% csrf_token %}
  <p>
    <input id="id_username" class="form-control" type="text" name="username" placeholder="Имя пользователя" required=""
      autofocus="">
  </p>
  <p>
    <input id="id_password" class="form-control" type="password" name="password" placeholder="Пароль" required="">
  </p>
  <p>
    <button type="submit" class="btn btn-primary btn-block">Войти</button>
  </p>
</form>

<div class="row justify-content-between">
  <div class="col">
    <a href="{% url 'authapp:register' %}"><small>Регистрация</small></a>
  </div>
  <div class="col">
    <a href="#"><small>Забыли пароль?</small></a>
  </div>
</div>
{% endblock %}

authapp/templates/authapp/user_form.html
{% extends 'authapp/base.html' %}
{% block content %}
{% load crispy_forms_tags %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <p>
        <button type="submit" class="btn btn-primary btn-block">Зарегистрироваться</button>
    </p>
</form>
<p>
<div class="row justify-content-between">
    <div class="col">
        <a href="{% url 'authapp:login' %}"><small>Войти</small></a>
    </div>
    <div class="col">
        <a href="#"><small>Забыли пароль?</small></a>
    </div>
</div>
</p>

{% endblock %}

{% block js %}

<script>
    $(document).ready(function () {
        {% if messages %}
        // Toasts
        $(".toast").toast({ delay: 5000 });
        $(".toast").toast("show");
        {% endif %}
    });
</script>

{% endblock %}